atom = :atom
also_atom = AlsoAtom
string = "I'm a string"
integer = 42
float = 3.1415
boolean = true
bits = ...
tuple = {"one", 2, :three}
list = ["one", 2, :three]
map = %{name: "Frodo", race: :hobbit, age: 40}
